### ISSUE TITLE
リリースノート確認用

### ISSUE THREAD

**Issue by np-yuando** [np-yuando/template#2]
s

**Comment by np-yuando** [comment]
- [x] 表示できないStorybookを修正 #3067 
- [x] 非公開メッセージ一覧でテナント管理者以外は自分か開催者のものだけにする #3066 
- [x] エクセルファイル入出力モジュールを xlsx から exceljs に変更 #3062 
- [x] メッセージグループ一覧Queryのレスポンスの開催者フラグを修正 #3060 
- [x] MessageGroupParticipantレコードの絞り込み条件の不要なvisible、openedを削除 #3059 
- [x] test:vtl、test:backend、amplify-function:buildコマンド改善の修正 #3058 
- [x] 組織ユーザードメインのユーザー用企業一覧APIを実行するQueryを追加 #3056 
- [x] メッセージグループ削除と非表示およびメッセージ画面デザイン見直し対応 #3054 
- [x] バックエンド開発で利用するtest:vtl、test:backend、amplify-function:buildコマンドを改善 #3053 
- [x] メッセージグループ一覧Queryの検索条件にオープンフラグを追加 #3052 
- [x] メッセージグループ一覧Queryのレスポンスにオープンフラグや表示切替者情報を追加 #3050 
- [x] 業務連絡タイトル検索でバックスラッシュが検索できる #3049 
- [x] フロントエンドから受け取るS3オブジェクトキーのチェックを強化 #3048 
- [x] version up: 1.8.11 → 1.8.12 #3047 
- [x] 管理画面テナント設定画面の vue エラーを修正 #3046 
- [x] ログイン処理で想定外のエラーログが amplify/analytics に記録されてしまう問題対処 #3045 
- [x] フロントエンドで使用している本部、エリア従業員一覧取得を"getEmployeesOfHeadofficeAndArea2"に変更 #3043 
- [x] Lambda版の本部、エリア従業員一覧取得APIを getEmployeesOfHeadofficeAndArea にリネーム #3041 
- [x] 回覧のやること一覧に業務連絡タイトルを表示 #3040 
- [x] 申込集計入力表から表示される画像ダイアログの画像サイズを大きく変更 #3039 
- [x] 管理者用メッセージ投稿検索Queryに抽出条件(送信者、グループ名、ファイル名)を追加 #3038 
- [x] VM Manager 画像一括ダウンロード条件フォームクリアに関する修正 #3037 
- [x] VTL版の本部、エリア従業員一覧取得API"getEmployeesOfHeadofficeAndArea"を削除 #3036 
- [x] メッセージグループの閉鎖できるユーザについて division まで含めて権限チェックするように修正 #3035 
- [x] 閉鎖されたメッセージグループでは削除等メニューを出さないように修正 #3033 
- [x] デフォルト役割ふせん設定機能フロントエンド #3027 
- [x] 業務連絡要確認一覧のテーブルヘッダラベルの間違いを修正 #3026 
- [x] 本部、エリア従業員一覧取得APIをLambdaで作成 #3023 
- [x] 要確認業務連絡の確認済みリスト修正 #3020 
- [x] 独自に設定していた旧WAF設定を削除し、Amplifyカスタムで再設定 #3016 
- [x] やること番号のデザインを統一した #3011 
- [x] 本部要確認CC機能フロントエンド #2996 
- [x] 宛先グループ機能バックエンド #2995 
- [x] Lintチェックでエラーになる不要なコメントを削除 @ktakemoto223 (#1066)
- [x] ユーザー用 API に企業一覧取得を追加 @ktakemoto223 (#1065)
- [x] Update README.md @atagawa (#1063)
- [ ] Releasing/v1.23.6 を master にマージ @ktakemoto223 (#1062)
- [x] 外部連携ドキュメントサイトにヘルスチェック用としてBASIC認証なしのURLを１つ追加 @ktakemoto223 (#176)
- [x] メッセージ削除機能の実装 @satoyan (#921)
- [x] 業務連絡のやることステータスの変更でローディングが止まらず、ステータス変更ボタンが非活性のままに @satoyan (#1017)
- [x] メッセージグループの画像投稿を削除する術がない @satoyan (#1014)
- [x] メッセージ削除後に入力フォームが非活性のままになる @satoyan (#1010)
- [x] メッセージグループの投稿を削除できない @satoyan (#1008)
- [x] メッセージグループタイトルが長い見切れる（開発時はオーバーフローエラー） @satoyan (#993)
- [x] VMミッション更新後にプルダウンリフレッシュすると更新したVMミッションの画像がずっとロード中になる @satoyan (#987)
- [x] S3にアップするキーに含むテナントIDが空になることがないかの調査 @satoyan (#955)
- [x] S3にアップするキーに含むテナントIDが店舗IDになることがないかの調査 @satoyan (#953)
- [x] VM画像登録の引数imagesの配列要素数がゼロになることがある @satoyan (#951)

## [ ] 🧰 Maintenances

- [ ] Bump up build number @github-actions (#1018)
- [x] Bump up build number @github-actions (#1015)
- [x] Bump up build number @github-actions (#1013)
- [x] Bump up build number @github-actions (#1011)
- [x] Bump up build number @github-actions (#1002)
- [x] chore(deps): bump firebase\_crashlytics from 3.4.14 to 3.4.15 @dependabot (#1000)
- [x] chore(deps): bump freezed from 2.4.5 to 2.4.7 @dependabot (#999)
- [x] chore(deps): bump custom\_lint from 0.6.0 to 0.6.2 @dependabot (#997)
- [x] chore(deps): bump amplify\_authenticator from 1.5.1 to 1.5.3 @dependabot (#996)
- [x] feat/upgurade flutter 3 19 1 @satoyan (#1001)
- [x] Bump up build number @github-actions (#995)
- [x] Bump up build number @github-actions (#994)
- [x] Bump up build number @github-actions (#991)
- [x] ボトムナビの各タブで状態を保持させないようにする @satoyan (#990)
- [ ] Bump up build number @github-actions (#988)
- [x] ボトムナビの使用され方が変則的 @satoyan (#980)
- [x] Bump up build number @github-actions (#981)
- [x] chore(deps): bump permission\_handler from 11.1.0 to 11.3.0 @dependabot (#979)
- [x] chore(deps): bump device\_info\_plus from 9.1.1 to 9.1.2 @dependabot (#978)
- [x] chore(deps): bump riverpod\_generator from 2.3.9 to 2.3.11 @dependabot (#977)
- [x] chore(deps): bump share\_plus from 7.2.1 to 7.2.2 @dependabot (#976)
- [x] chore(deps): bump go\_router from 13.1.0 to 13.2.0 @dependabot (#975)
- [x] Bump up build number @github-actions (#974)
- [x] VMミッション画面のパフォーマンス改善 @satoyan (#973)
- [x] Bump up build number @github-actions (#971)
- [x] サブ担当者更新後にわたし宛てリトも最新化 @satoyan (#970)
- [x] Bump up build number @github-actions (#969)
- [x] [iOS] メッセージ画面でホームバー（最下部中央にある横棒みたいなもの）とUIが被っている @satoyan (#968)
- [x] Bump up build number @github-actions (#962)
- [x] chore(deps): bump flutter\_animate from 4.3.0 to 4.5.0 @dependabot (#957)
- [x] chore(deps): bump mime from 1.0.4 to 1.0.5 @dependabot (#958)
- [x] chore(deps): bump image\_picker from 1.0.5 to 1.0.7 @dependabot (#959)
- [x] chore(deps): bump amplify\_auth\_cognito from 1.6.0 to 1.6.2 @dependabot (#960)
- [x] chore(deps): bump custom\_lint from 0.5.7 to 0.6.0 @dependabot (#961)
- [ ] Bump up build number @github-actions (#956)
- [x] Bump up build number @github-actions (#954)
- [x] Bump up build number @github-actions (#952)
- [ ] Bump up build number @github-actions (#946)
- [ ] Version up for 1.0.17 @ktakemoto223 (#945)
- [x] Bump up build number @github-actions (#944)
- [x] Podfile.lock更新 @satoyan (#943)
- [x] Bump up build number @github-actions (#937)
- [x] chore(deps): bump url\_launcher from 6.2.1 to 6.2.4 @dependabot (#936)
- [x] chore(deps): bump hooks\_riverpod from 2.4.9 to 2.4.10 @dependabot (#935)
- [x] chore(deps): bump flutter\_hooks from 0.20.3 to 0.20.4 @dependabot (#934)
- [x] chore(deps): bump cached\_network\_image from 3.3.0 to 3.3.1 @dependabot (#933)
- [x] chore(deps): bump firebase\_crashlytics from 3.4.9 to 3.4.13 @dependabot (#932)
- [x] Bump up build number @github-actions (#924)
- [x] chore(deps): bump uuid from 3.0.7 to 4.3.3 @dependabot (#918)
- [x] chore(deps): bump firebase\_database from 10.3.6 to 10.4.0 @dependabot (#917)
- [x] ワークフローのレビュアーを変更 @atagawa (#925)
- [x] chore(deps): bump build\_runner from 2.4.7 to 2.4.8 @dependabot (#916)
- [x] chore(deps): bump graphql\_codegen from 0.13.9 to 0.13.11 @dependabot (#915)
- [x] chore(deps): bump go\_router from 13.0.1 to 13.1.0 @dependabot (#914)
- [x] dependabot.ymlの更新 @atagawa (#923)
